<Strong> <font face="Verdana" size="5"> AML Country Resolution - Dummy Data Creation </font></strong> <br>
<b> <font face="Verdana" size="3"> Project Highlight: </font></b><br>
<font face="Verdana" size="3"> This is the exact replica of the work which was carried out on a real project at one of the banks. </font><br>
<b> <font face="Verdana" size="3"> Project Objective: </font></b><br>
<font face="Verdana" size="3"> Since due to data privacy issue real unstructured ISO 20022 SWIFT pacs.008 messages could not be used for this project, a dataset of dummy addresses must be created. Address datasets belonging to 25 countries, one for each country will be concatenated into one large dataset. For model validation purpose the field which records the correct country ISO code will be included in this final dataset. </font><br>
<b> <font face="Verdana" size="3">Data Scientist:</font></b><font face="Verdana" size="3"> Henry J. Hu</font><br>
<b> <font face="Verdana" size="3">Programming Language:</font></b><font face="Verdana" size="3"> Python</font><br>
<b> <font face="Verdana" size="3"> Data Source: </font></b><br>
<font face="Verdana" size="3"> Data Owner: </font> <a href="https://postalcodezip.com ">postalcodezip.com</a> <br>
<font face="Verdana" size="3"> Number of Countries: </font> 25 <br>
<font face="Verdana" size="3"> Number of Addresses: </font> 2290 <br>
<b> <font face="Verdana" size="3"> Data Privacy: </font></b><br>
<font face="Verdana" size="3"> 
Because company policy requires all employees to sign a Non-Disclosure Agreement (NDA) that prohibits the disclosure of confidential information related to the company’s data and business operations, this replica machine learning project uses only freely and publicly accessible data. The project does not disclose or contain any confidential information related to any company’s data, operations, or business practices.
</font><br>
<b> <font face="Verdana" size="3">Last Update:</font></b><font face="Verdana" size="3"> October 21st, 2026</font>

# Importing Python Libraries

In [3]:
import sys
import pandas as pd
import numpy as np
import ollama
import json
import requests
import os
import random

# Merging Data

In [5]:
os.chdir("C:/Users/henry/Jupyter_Home/Data/Addresses/Street_Addresses/")
folder_path = os.getcwd()

# Collect Excel-like files
excel_files = [
    f for f in os.listdir(folder_path)
    if f.endswith(('.xlt', '.xls', '.xlsx'))
]

all_data = []
failed_files = []

for file in excel_files:
    full_path = os.path.join(folder_path, file)

    try:
        # Choose engine based on extension
        if file.endswith(('.xls', '.xlt')):
            df = pd.read_excel(full_path, engine='xlrd')
        else:
            df = pd.read_excel(full_path, engine='openpyxl')

        df['source_file'] = file  # optional tracking column
        all_data.append(df)

    except Exception as e:
        print(f"Failed to read {file}: {e}")
        failed_files.append(file)

# Merge all at once (faster than repeated concat)
if all_data:
    merged_df = pd.concat(all_data, ignore_index=True)
else:
    merged_df = pd.DataFrame()

# Save output
os.chdir("C:/Users/henry/Jupyter_Home/Data/Addresses/Merged_Addresses/")
folder_path = os.getcwd()
output_file = os.path.join(folder_path, 'merged_output.xlsx')
merged_df.to_excel(output_file, index=False)

print("\n Merge Completed")
print(f"Files processed: {len(excel_files)}")
print(f"Successfully merged: {len(all_data)}")
print(f"Failed files: {len(failed_files)}")

if failed_files:
    print("\nFailed list:")
    for f in failed_files:
        print(" -", f)

 Merge Completed
Files processed: 25
Successfully merged: 25
Failed files: 0

# Import Merged Data File

In [7]:
df = pd.read_excel (r"C:/Users/henry/Jupyter_Home/Data/Addresses/Merged_Addresses/merged_output.xlsx", index_col=None)

In [8]:
df = df.replace(np.nan, '')

In [9]:
df = df.astype(str)

In [10]:
df.shape

(2290, 18)

In [11]:
df.dtypes

Country Code        object
Country             object
Region              object
City                object
Postal Code         object
Street              object
Number              object
Latitude            object
Longitude           object
Elevation (m)       object
source_file         object
State               object
Province            object
District            object
District Sinhala    object
District Tamil      object
City Sinhala        object
City Tamil          object
dtype: object

In [12]:
df.isnull().sum()

Country Code        0
Country             0
Region              0
City                0
Postal Code         0
Street              0
Number              0
Latitude            0
Longitude           0
Elevation (m)       0
source_file         0
State               0
Province            0
District            0
District Sinhala    0
District Tamil      0
City Sinhala        0
City Tamil          0
dtype: int64

In [13]:
df.head(n=2)

,Country Code,Country,Region,City,Postal Code,Street,Number,Latitude,Longitude,Elevation (m),source_file,State,Province,District,District Sinhala,District Tamil,City Sinhala,City Tamil
0,AR,Argentina,Buenos Aires,Banfield,B1827 DIA,Calle Paz General,,-34.750135,-58.440425,6.0,postalcodezip_argentina_addresses_sample.xls,,,,,,,
1,AR,Argentina,Córdoba,Marcos Juárez,X2580 DJN,Calle José Hernández,,-32.91159,-62.460756,97.0,postalcodezip_argentina_addresses_sample.xls,,,,,,,

In [14]:
df.tail(n=2)

,Country Code,Country,Region,City,Postal Code,Street,Number,Latitude,Longitude,Elevation (m),source_file,State,Province,District,District Sinhala,District Tamil,City Sinhala,City Tamil
2288,YE,Yemen,Hadramaut Governorate,Kunah,,طريق وادي عدم,,15.335451,48.666242,1096.0,postalcodezip_yemen_addresses_sample.xls,,,,,,,
2289,YE,Yemen,Dhamar Governorate,Az Zahrah,778657,نقيل حميدة,,14.299983,43.820073,1276.0,postalcodezip_yemen_addresses_sample.xls,,,,,,,

In [15]:
df.dtypes

Country Code        object
Country             object
Region              object
City                object
Postal Code         object
Street              object
Number              object
Latitude            object
Longitude           object
Elevation (m)       object
source_file         object
State               object
Province            object
District            object
District Sinhala    object
District Tamil      object
City Sinhala        object
City Tamil          object
dtype: object

In [16]:
df.head(n=2)

,Country Code,Country,Region,City,Postal Code,Street,Number,Latitude,Longitude,Elevation (m),source_file,State,Province,District,District Sinhala,District Tamil,City Sinhala,City Tamil
0,AR,Argentina,Buenos Aires,Banfield,B1827 DIA,Calle Paz General,,-34.750135,-58.440425,6.0,postalcodezip_argentina_addresses_sample.xls,,,,,,,
1,AR,Argentina,Córdoba,Marcos Juárez,X2580 DJN,Calle José Hernández,,-32.91159,-62.460756,97.0,postalcodezip_argentina_addresses_sample.xls,,,,,,,

In [17]:
df.tail(n=2)

,Country Code,Country,Region,City,Postal Code,Street,Number,Latitude,Longitude,Elevation (m),source_file,State,Province,District,District Sinhala,District Tamil,City Sinhala,City Tamil
2288,YE,Yemen,Hadramaut Governorate,Kunah,,طريق وادي عدم,,15.335451,48.666242,1096.0,postalcodezip_yemen_addresses_sample.xls,,,,,,,
2289,YE,Yemen,Dhamar Governorate,Az Zahrah,778657,نقيل حميدة,,14.299983,43.820073,1276.0,postalcodezip_yemen_addresses_sample.xls,,,,,,,

In [18]:
#char_pool = np.array([' ', ',', ':', '.', '-', '#', '@', '&'])
char_pool = np.array([' ', ','])
df['Street'] = df['Street'] + [random.choice(char_pool) for _ in range(len(df))]
df['Region'] = df['Region']  + [random.choice(char_pool) for _ in range(len(df))]
df['City'] = df['City']  + [random.choice(char_pool) for _ in range(len(df))]
df['State'] = df['State']  + [random.choice(char_pool) for _ in range(len(df))]
df['Province'] = df['Province']  + [random.choice(char_pool) for _ in range(len(df))]
df['District'] = df['District']  + [random.choice(char_pool) for _ in range(len(df))]

In [19]:
df.head(n=5)

,Country Code,Country,Region,City,Postal Code,Street,Number,Latitude,Longitude,Elevation (m),source_file,State,Province,District,District Sinhala,District Tamil,City Sinhala,City Tamil
0,AR,Argentina,Buenos Aires,Banfield,B1827 DIA,Calle Paz General,,-34.750135,-58.440425,6.0,postalcodezip_argentina_addresses_sample.xls,",",",",,,,,
1,AR,Argentina,Córdoba,Marcos Juárez,X2580 DJN,"Calle José Hernández,",,-32.91159,-62.460756,97.0,postalcodezip_argentina_addresses_sample.xls,",",",",",",,,,
2,AR,Argentina,Buenos Aires,"Tandil,",B7000 CTA,"Calle Tab,",,-37.332783,-59.148708,223.0,postalcodezip_argentina_addresses_sample.xls,",",,",",,,,
3,AR,Argentina,"Buenos Aires,",Berazategui,B1884 KKN,Calle Tab,,-34.7863,-58.223026,15.0,postalcodezip_argentina_addresses_sample.xls,",",",",",",,,,
4,AR,Argentina,Buenos Aires,"San Miguel,",B1663 GXN,Calle General Justo Jose de Urquiza,,-34.549197,-58.727449,31.0,postalcodezip_argentina_addresses_sample.xls,,,",",,,,

In [20]:
df.dtypes

Country Code        object
Country             object
Region              object
City                object
Postal Code         object
Street              object
Number              object
Latitude            object
Longitude           object
Elevation (m)       object
source_file         object
State               object
Province            object
District            object
District Sinhala    object
District Tamil      object
City Sinhala        object
City Tamil          object
dtype: object

In [21]:
# Set 'employee_id' as the new index
df = df.set_index('Country Code')

In [22]:
df_final = pd.Series(df[['Number', 'Street', 'Region', 'City', 'State', 'Province', 'District', 'Postal Code']].agg(' '.join, axis=1),name='Address').to_frame()

In [23]:
df_final.tail(n=5)

                                                        Address
Country Code
YE             طريق جعفر قحفة الكسير  Ta'izz Governorate  Hu...
YE             طريق مأرب - عتق, Marib Governorate  Ya`arah, ...
YE             طريق وادي رمع  Dhamar Governorate  Huqayla,  ...
YE             طريق وادي عدم, Hadramaut Governorate  Kunah, ...
YE             نقيل حميدة, Dhamar Governorate, Az Zahrah  , ...

In [24]:
df_final = df_final.reset_index()

In [25]:
df_final = df_final.rename(columns={"Country Code": "CountryCodeVerified"})

In [26]:
df_final.tail(n=5)

     CountryCodeVerified                                            Address
2285                  YE   طريق جعفر قحفة الكسير  Ta'izz Governorate  Hu...
2286                  YE   طريق مأرب - عتق, Marib Governorate  Ya`arah, ...
2287                  YE   طريق وادي رمع  Dhamar Governorate  Huqayla,  ...
2288                  YE   طريق وادي عدم, Hadramaut Governorate  Kunah, ...
2289                  YE   نقيل حميدة, Dhamar Governorate, Az Zahrah  , ...

In [27]:
df_final.insert(0, 'MessageType', 'pacs.008')

In [28]:
df_final.tail(n=5)

,MessageType,CountryCodeVerified,Address
2285,pacs.008,YE,طريق جعفر قحفة الكسير Ta'izz Governorate Hu...
2286,pacs.008,YE,"طريق مأرب - عتق, Marib Governorate Ya`arah, ..."
2287,pacs.008,YE,"طريق وادي رمع Dhamar Governorate Huqayla, ..."
2288,pacs.008,YE,"طريق وادي عدم, Hadramaut Governorate Kunah, ..."
2289,pacs.008,YE,"نقيل حميدة, Dhamar Governorate, Az Zahrah , ..."

In [29]:
df_final.to_excel(r"C:/Users/henry/Jupyter_Home/Data/Addresses/Merged_Addresses/LLM_Addresses.xlsx", index=False)